---
# Apply latest Ruby style guide and newly introduced cops
AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

  Exclude:
    - '_snippets/**/*'
  Include:
  - 'Gemfile'
  - 'Rakefile'
  - '**/*.rb'

# Ignore block length where unavoidable (e.g., frameworks using blocks)
Metrics/BlockLength:
  Enabled: true
  Exclude:
    - 'spec/**/*'
    - 'Rakefile'

# See: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/MultilineMethodCallIndentation
Layout/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/HashSyntax:
  Enabled: true
  Exclude:
    - 'Rakefile'
