---
# Name your file secrets.yml

development:
  DB_FILENAME: db/local/dev.db
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_d

test:
  DB_FILENAME: db/local/test.db
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_d

production:
  INSTAGRAM_TOKEN: create_instagram_api_token
  ACCOUNT_ID: create_instagram_account_d